### ISSUE TITLE
Error when starting transaction

### ISSUE THREAD

**Issue by BboyKeen** [subzerobo/elastic-apm-php-agent#3]
Hi

I face a weird error when just starting a transaction coming from Protobuf internals.

`Error occurred during parsing: Error occurred during parsing: String field only accepts string value`

The error happens during the transactionEvent->setRequest() call. 

Here is the stack trace

```
Google\Protobuf\Internal\GPBDecodeException
in vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php (line 1256)
in vendor/google/protobuf/src/Google/Protobuf/Internal/Message.php->parseFromJsonStream (line 742)
in vendor/subzerobo/elastic-apm-php-agent/src/Wrappers/Traits/EventTrait.php->mergeFromJsonString (line 290)
in vendor/subzerobo/elastic-apm-php-agent/src/Wrappers/Traits/EventTrait.php->setRequest (line 101)
in vendor/subzerobo/elastic-apm-php-agent/src/Wrappers/TransactionEvent.php->initContext (line 52)
in vendor/subzerobo/elastic-apm-php-agent/src/Factories/DefaultEventFactory.php->__construct (line 51)
in vendor/subzerobo/elastic-apm-php-agent/src/ApmAgent.php->createTransaction (line 132)
ApmAgent->startTransaction()
```

It's as if the output of json_encoding my request has a wrong structure.
Did you face this someday ?

**Comment by subzerobo** [comment]
Hi
Not this bug really but sometimes I face similar problems with Google Protobuf Code-Generator and I've tried to fix them in the project like int64 serialization and other things like that.

Could you please drop the output of [$contextRequestArr](https://github.com/subzerobo/elastic-apm-php-agent/blob/472efd2077153c68d922a8e8ca915400ba26e5f0/src/Wrappers/Traits/EventTrait.php#L263) in this line so we can check the array which has been serialized?
Google Protobuf default code generator has weird bugs sometimes.

**Comment by BboyKeen** [comment]
Well, after investigation, it looks like that having a nested array in `$env` produces the error.

However, the nested array is not of my choice, it's `argv` from the php process..

```
env : [
...

  "SCRIPT_FILENAME" => "/var/www/symfony/public/index.php"
  "REDIRECT_STATUS" => "200"
  "SERVER_NAME" => "yogosha.local"
  "SERVER_PORT" => "443"
  "SERVER_ADDR" => "172.10.0.4"
  "REMOTE_PORT" => "47798"
  "REMOTE_ADDR" => "172.10.0.254"
  "SERVER_SOFTWARE" => "nginx/1.10.3"
  "GATEWAY_INTERFACE" => "CGI/1.1"
  "HTTPS" => "on"
  "REQUEST_SCHEME" => "https"
  "SERVER_PROTOCOL" => "HTTP/1.1"
  "DOCUMENT_ROOT" => "/var/www/symfony/public"
  "DOCUMENT_URI" => "/index.php//_wdt/52098f"
  "REQUEST_URI" => "/_wdt/52098f"
  "SCRIPT_NAME" => "/index.php"
  "CONTENT_LENGTH" => ""
  "CONTENT_TYPE" => ""
  "REQUEST_METHOD" => "GET"
  "QUERY_STRING" => ""
  "FCGI_ROLE" => "RESPONDER"
  "PHP_SELF" => "/index.php"
  "REQUEST_TIME_FLOAT" => 1565363945.5224
  "REQUEST_TIME" => 1565363945
  "argv" => []
  "argc" => 0

...
]
```

**Comment by BboyKeen** [comment]
I'm not sure it's worth it to modify the protobuf definition for that.

I think imploding the nested arrays recursively would do the trick.

**Comment by BboyKeen** [comment]
Working solution in EventTrait.php

```
final protected function getEnv()
{
        $envMask = $this->sharedData->getEnvWhiteListKeys();
        $env = empty($envMask)
            ? $_SERVER
            : array_intersect_key($_SERVER, array_flip($envMask));

        array_walk($env, function(&$value) {
            if (is_array($value)) {
                $value = json_encode($value);
            }
        });
        return (object) $env;
}
```

**Comment by subzerobo** [comment]
> I'm not sure it's worth it to modify the protobuf definition for that.
> 
> I think imploding the nested arrays recursively would do the trick.

Hi Kevin,
It's a good trick because the APM is not supporting the nested key-value in the definition too.
